@startuml

package Main {

    class Game {
        +widthMap: int
        +heightMap: int
        -center: ControlCenter
        -map: Cells[]
        +step():void
        Определяет общее движение всей игры
        Определяет кол-во исполнителей
        Определяет карту
        Определяет конечную цель - что и сколько собрать
        Генерирует цели сбора и расбрасывает по карты
    }

    Enum Cell {
    Определяет виды клеток
        +Ground
        +Water
    }


    class Canvas {
        -map: Cell[]
        -widthCell: int
        +setMap(Cell[] cell):void
        +clear():void
        +draw():void
        Отрисовка поля и элементов
    }


    class Compiler {
        Переводит алгоритм, написанный пользователем
        в понятную последовательность команд для программы
    }

}

package controllers {
    class MainController {
        +startTimer():void
        Контроллер окна
        Определяет инициализацию и поведение окна
    }
}

@enduml